pipeline {
  agent any
  tools {
    maven 'Maven 3.8.5'
  }
  stages {
    stage("build") {
      when{        
        changeset '**/worker'
      }
      steps {
        echo 'Compiling worker app'
        sh 'ls -l'
        dir('worker'){
            sh 'mvn compile'
        }
      }
    }
    stage("test") {
      when{        
        changeset '**/worker'
      }
      steps {
        echo 'Running Unit Tets on worker app'
        dir('worker'){
            sh 'mvn clean test'
        }
      }
    }
    stage("package") {
      when{
        branch 'master'
        changeset '**/worker'
      }
      steps {
        echo 'Packaging worker app'
        dir('worker'){
            sh 'mvn packege -DskipTests'
        }
      }
    }
  }
  post {
    success{
      slackSend "Build Finished - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
    }
    always {
      echo 'Building multibranch pipeline for worker is completed..'
      
    }
  }
}
