pipeline {
  agent any
  tools {
    maven 'Maven 3.8.5'
  }
  stages {
    stage("build") {
      steps {
        echo 'Compiling worker app'
        dir('worker'){
            sh 'cd worker && mvn compile'
        }
      }
    }
    stage("test") {
      steps {
        echo 'Running Unit Tets on worker app'
      }
    }
    stage("package") {
      steps {
        echo 'Packaging worker app'
      }
    }
  }
  post {
    always {
      echo 'Building multibranch pipeline for worker is completed..'
    }
  }
}